pipeline {

    agent any

    tools {
        jdk 'JDK20'
        maven 'Maven'
    }

    environment {

        IMAGE = "gopikrishnachodapaneedi/springboot-demo"

        SCANNER_HOME = tool 'SonarScanner'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('springboot-demo') {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }

        stage('SonarQube') {
            steps {
                dir('springboot-demo') {

                    withSonarQubeEnv('SonarQube') {

                        sh """
                        ${SCANNER_HOME}/bin/sonar-scanner \
                        -Dsonar.projectKey=springboot-demo \
                        -Dsonar.sources=src \
                        -Dsonar.java.binaries=target/classes
                        """
                    }
                }
            }
        }

        stage('Quality Gate') {
            steps {
                timeout(time:5, unit:'MINUTES') {
                    waitForQualityGate abortPipeline:true
                }
            }
        }

        stage('Docker Build') {
            steps {

                dir('springboot-demo') {

                    sh """
                    docker build -t ${IMAGE}:${BUILD_NUMBER} .
                    docker tag ${IMAGE}:${BUILD_NUMBER} ${IMAGE}:latest
                    """
                }
            }
        }

        stage('Docker Login') {

            steps {

                withCredentials([usernamePassword(
                credentialsId:'dockerhub-creds',
                usernameVariable:'USER',
                passwordVariable:'PASS')]) {

                    sh '''
                    echo $PASS | docker login -u $USER --password-stdin
                    '''
                }
            }
        }

        stage('Docker Push') {

            steps {

                sh '''
                docker push gopikrishnachodapaneedi/springboot-demo:latest
                '''
            }
        }

        stage('Update Manifest') {

            steps {

                sh '''
                sed -i "s|image:.*|image: gopikrishnachodapaneedi/springboot-demo:${BUILD_NUMBER}|g" k8s-manifests/deployment.yaml
                '''
            }
        }

        stage('Git Push') {

            steps {

                withCredentials([usernamePassword(
                credentialsId:'github-creds',
                usernameVariable:'USER',
                passwordVariable:'TOKEN')]) {

                    sh '''
                    git config user.email "jenkins@local"
                    git config user.name "Jenkins"

                    git add .

                    git commit -m "Updated image ${BUILD_NUMBER}" || true

                    git push https://${USER}:${TOKEN}@github.com/gopikrishnac/Devops2.git HEAD:main
                    '''
                }
            }
        }
    }
}